language: node_js
sudo: false
node_js:
  - "node"
  install: npm install
cache:
  directories:
    - node_modules
notifications:
  email: false
before_script:
  - psql -c 'CREATE test; -U postgres'
scripts:
  - npm run test
services:
  - 
after_success:
  - npm run coverage