language: node_js
sudo: false
node_js:
  - "node"
cache:
  directories:
    - node_modules
notifications:
  email: false
before_script:
- npm install
scripts:
  - npm run test
  - npm run build
after_success: npm run coveralls

deploy:
provider: pages
skip-cleanup: true
github-token: $GITHUB_TOKEN
on:
  branch: develop