language: node_js
sudo: false
node_js:
  - "stable"
cache:
  directories:
    - node_modules
notifications:
  email: false
before_script:
- npm install
scripts:
  - npm run test
after_success: npm run coveralls